### ISSUE TITLE
Cannot scroll mouse wheel in win 10 start menu when running this script

### ISSUE THREAD

**Issue by xgdgsc** [chanz/CustomMouseGestures#1]
Thanks for your work. I use it mainly as browser mouse gestures. But I found when running it, I cannot scroll mouse wheel in win 10 start menu and some other apps.

**Comment by chanz** [comment]
Sorry for the late answer. You can add the the start menu to the ignore list by hovering your mouse over the start menu and then press ctrl+f2 (undocumented feature). In the right bottom corner a tray tip should indicate which process has been added to the ignore list.

You can edit the CustomMouseGestures.ini as well.

As example my CustomMouseGestures.ini:
[Settings]
IgnoreProcesses=Factorio.exe|starbound.exe|javaw.exe|VpxClient.exe|SystemSettings.exe|KSP.exe|mstsc.exe
AllowProcesses=explorer.exe|firefox.exe

**Comment by xgdgsc** [comment]
Thanks!
